<p align="center">
  <img src="fotoGraduacion.png" width="160" style="border-radius: 50%;">
</p>

title: "Alberto del Río Jara"
description: "M.S. in Statistics and Computer Analytics student. Passionate about AI, embedded systems, and data."
theme: jekyll-theme-cayman

# Optional: your GitHub username and repo for links
github_username: albertodelrio
repository: albertodelrio/albertodelrio.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
